version: "3.9"
services:
  # Proxy to link services to subdomains.
  traefik:
    image: "traefik:v2.4.12"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    extra_hosts:
      - host.docker.internal:172.17.0.1
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: "always"
  # Blocking adds and DNS-server. 
  # pihole:
  #   image: "pihole/pihole:v5.8.1"
  #   container_name: "pihole"
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #   environment:
  #     - TZ=Europe/Helsinki
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN}`)"
  #     - "traefik.http.routers.pihole.entrypoints=web"
  #     - "traefik.http.services.pihole.loadbalancer.server.port=80"
  #   volumes:
  #     - "pihole:/etc/pihole/"
  #     - "pihole_dnsmasq:/etc/dnsmasq.d/"
  #   depends_on:
  #     - "traefik"
  #   restart: "always"
  # Download MyAnimeList lists.
  myanimelist_downloader:
    image: "ghcr.io/santerihetekivi/myanimelist_downloader:main"
    container_name: myanimelist_downloader
    volumes:
      - "mal_list_downloader:/app/downloads"
      - "./myanimelist_downloader.env:/app/.env"
    command: myanimelist_downloader --download-directory='/app/downloads' --env-file='/app/.env' --anime --manga
    restart: "no"
  # Database for hetekivi.com.
  db:
    image: "postgres:13.3-buster"
    container_name: "db"
    environment:
      - TZ=Europe/Helsinki
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGID=1020
      - PUID=1020
    volumes:
      - "hetekivi_postgresql:/var/lib/postgresql/data/"
    restart: "always"
  # Encoding and storing lists.
  hetekivi.com:
    image: "ghcr.io/santerihetekivi/hetekivi.com:master"
    container_name: "hetekivi.com"
    environment:
      - TZ=Europe/Helsinki
      - PGID=1020
      - PUID=1020
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hetekivi.rule=Host(`hetekivi.${DOMAIN}`)"
      - "traefik.http.routers.hetekivi.entrypoints=web"
      - "traefik.http.services.hetekivi.loadbalancer.server.port=8000"
    volumes:
      - "hetekivi_web:/data/"
      - "hetekivi_tmp:/tmp/"
    depends_on:
      - "traefik"
      - "db"
    restart: "always"
  # Home automation.
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:2021.7.4"
    container_name: "homeassistant"
    environment:
      - TZ=Europe/Helsinki
    privileged: true
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${DOMAIN}`)"
      - "traefik.http.routers.homeassistant.entrypoints=web"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
    volumes:
      - "homeassistant:/config"
    depends_on:
      - "traefik"
    restart: "always"
  # Media server.
  plex:
    image: "linuxserver/plex:1.26.2.5797-5bd057d2b-ls118"
    container_name: "plex"
    environment:
      - TZ=Europe/Helsinki
      - VERSION=latest
      - PUID=1000
      - PGID=1000
    env_file:
      - plex.env
    volumes:
      - "plex_config:/config"
      - "plex_transcode:/transcode"
      - "plex_media:/data"
    ports:
      - "32400:32400/tcp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
    restart: "always"
  # Media server statics.
  tautulli:
    image: "tautulli/tautulli"
    container_name: "tautulli"
    environment:
      - TZ=Europe/Helsinki
      - PUID=1000
      - PGID=1000
    volumes:
      - "tautulli:/config"
      - "plex_logs:/plex_logs:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN}`)"
      - "traefik.http.routers.tautulli.entrypoints=web"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
    restart: "always"
# NFS volumes from NAS.
volumes:
  mal_list_downloader:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/mal_list_downloader"
  hetekivi_postgresql:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/hetekivi/postgresql"
  hetekivi_tmp:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/hetekivi/tmp"
  hetekivi_web:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/hetekivi/web"
  pihole:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/pihole/etc-pihole"
  pihole_dnsmasq:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/pihole/etc-dnsmasq.d"
  homeassistant:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/homeassistant"
  plex_config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/plex/config"
  plex_transcode:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/plex/transcode"
  plex_media:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/media"
  tautulli:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/tautulli"
  plex_logs:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,ro"
      device: ":/mnt/HDD_4T_CH_120G/rancher/plex/config/Library/Application Support/Plex Media Server/Logs"
