version: "3.9"
services:
  traefik:
    image: "traefik:v2.4.12"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    extra_hosts:
      - host.docker.internal:172.17.0.1
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
  pihole:
    image: "pihole/pihole:v5.8.1"
    container_name: "pihole"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=Europe/Helsinki
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN}`)"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    volumes:
      - "pihole:/etc/pihole/"
      - "pihole_dnsmasq:/etc/dnsmasq.d/"
    depends_on:
      - "traefik"
    restart: unless-stopped
  mal_list_downloader:
    image: "ghcr.io/santerihetekivi/mal_list_downloader:master"
    container_name: mal_list_downloader
    command: node /app/start.js
    volumes:
      - mal_list_downloader:/app/data
    environment:
      - TZ=Europe/Helsinki
      - HEADLESS=true
      - DOWNLOAD_TIME=2000
      - DEBUG=MALDownloader::*
    env_file:
      - mal_list_downloader.env
  db:
    image: "postgres:13.3-buster"
    container_name: "db"
    environment:
      - TZ=Europe/Helsinki
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGID=1020
      - PUID=1020
    volumes:
      - "hetekivi_postgresql:/var/lib/postgresql/data/"
  hetekivi.com:
    image: "ghcr.io/santerihetekivi/hetekivi.com:master"
    container_name: "hetekivi.com"
    environment:
      - TZ=Europe/Helsinki
      - PGID=1020
      - PUID=1020
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hetekivi.rule=Host(`hetekivi.${DOMAIN}`)"
      - "traefik.http.routers.hetekivi.entrypoints=web"
      - "traefik.http.services.hetekivi.loadbalancer.server.port=8000"
    volumes:
      - "hetekivi_web:/data/"
      - "hetekivi_tmp:/tmp/"
    depends_on:
      - "traefik"
      - "db"
    restart: unless-stopped
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:2021.7.4"
    container_name: "homeassistant"
    environment:
      - TZ=Europe/Helsinki
    privileged: true
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${DOMAIN}`)"
      - "traefik.http.routers.homeassistant.entrypoints=web"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
    volumes:
      - "homeassistant:/config"
    depends_on:
      - "traefik"
    restart: unless-stopped
  plex:
    image: "plexinc/pms-docker:latest"
    container_name: "plex"
    environment:
      - TZ=Europe/Helsinki
    env_file:
      - plex.env
    volumes:
      - "plex_config:/config"
      - "plex_transcode:/transcode"
      - "plex_media:/data"
    ports:
      - "32400:32400/tcp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.services.plex.loadbalancer.server.port=80"
volumes:
  mal_list_downloader:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/mal_list_downloader"
  hetekivi_postgresql:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/hetekivi/postgresql"
  hetekivi_tmp:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/hetekivi/tmp"
  hetekivi_web:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/hetekivi/web"
  pihole:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/pihole/etc-pihole"
  pihole_dnsmasq:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/pihole/etc-dnsmasq.d"
  homeassistant:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/homeassistant"
  plex_config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/plex/config"
  plex_transcode:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/rancher/plex/transcode"
  plex_media:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nolock,soft,rw"
      device: ":/mnt/HDD_4T_CH_120G/media"
